/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { AhmedNFT__factory } from "./AhmedNFT__factory";
export { BoobaToken__factory } from "./BoobaToken__factory";
